### ISSUE TITLE
Needs Improvement for Yellow Ver. 0.8.21

### ISSUE THREAD

**Issue by mhmadl** [GiovanniSalmeri/yellow-quiz#1]
I encountered some problems in regards with the visual running Yellow Ver. 0.8.21.  It does not perform as it performs in the previous Yellow.

**Comment by GiovanniSalmeri** [comment]
Thank you for the warning. I will take advantage of the vacation days to check everything.

**Comment by GiovanniSalmeri** [comment]
I have now updated the API, as soon as possible I will double-check that all in in order. Thank you!
